<?php
/** @package Phreeze.hendriknitsche.de::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("FavoriteMap.php");

/**
 * FavoriteDAO provides object-oriented access to the favorite table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Phreeze.hendriknitsche.de::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class FavoriteDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $PurchaseId;

	/** @var string */
	public $Note;


	/**
	 * Returns the foreign object based on the value of PurchaseId
	 * @return Purchase
	 */
	public function GetPurchase()
	{
		return $this->_phreezer->GetManyToOne($this, "favorite_ibfk_1");
	}


}
?>